version: '3.9'
services: 
  database: 
    image: postgres
    ports:
      - 5432:5432
    container_name: "db_container_maintenance"
    restart: always
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=maintenance
    volumes: 
    - pgdata:/data/postgres

  app:
    build: .
    container_name: maintenance
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes: 
  pgdata:
    driver: local
