import { prisma } from '.'

const newDepartments = [
  { name: 'Administração' },
  { name: 'Almoxarifado' },
  { name: 'Ambulatório' },
  { name: 'Banco de Sangue' },
  { name: 'Bloco Cirúrgico' },
  { name: 'Cardiologia' },
  { name: 'Cartão Saúde' },
  { name: 'Clinica Renal' },
  { name: 'CME' },
  { name: 'Compras' },
  { name: 'Contabilidade' },
  { name: 'Controladoria' },
  { name: 'Coordenação de Enfermagem' },
  { name: 'Covid' },
  { name: 'Farmácia' },
  { name: 'Faturamento' },
  { name: 'Financeiro' },
  { name: 'Governança' },
  { name: 'Internação' },
  { name: 'Jurídico' },
  { name: 'Laboratório' },
  { name: 'Maternidade' },
  { name: 'Nugetes' },
  { name: 'Nutrição' },
  { name: 'Quimioterapia' },
  { name: 'Radioterapia' },
  { name: 'Fisica' },
  { name: 'Projetos' },
  { name: 'CCIH' },
  { name: 'Coordenação PS' },
  { name: 'Núcleo' },
  { name: 'Pronto Socorro' },
  { name: 'Psicologia' },
  { name: 'Radiologia' },
  { name: 'RH' },
  { name: 'Same' },
  { name: 'Saúde Mental' },
  { name: 'SESMT' },
  { name: 'Tesouraria' },
  { name: 'TI' },
  { name: '2 Andar' },
  { name: '3 Andar' },
  { name: '4 Andar' },
  { name: '5 Andar' },
  { name: 'UTI Adulto' },
  { name: 'UTI Neo' },
  { name: 'Ucinco' },
]

const createManyDepartments = newDepartments.map((department) =>
  prisma.department.create({
    data: department,
  }),
)

Promise.all(createManyDepartments)
